import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  bottomModal: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flex: 1,
    backgroundColor: '#fff',
  },
  upcomingLaunchesContainer: {overflow: 'hidden'},
  launchHeader: {
    fontFamily: 'NunitoSans-Bold',
    fontSize: 18,
    fontWeight: '800',
  },
  contentContainer: {paddingHorizontal: 12},
  searchText: {
    fontFamily: 'NunitoSans-Bold',
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
  },
  launchContainer: {
    flexDirection: 'row',
    marginVertical: 10,
    height: 140,
    backgroundColor: '#e7ecef',
    width: Dimensions.get('window').width - 48,
    borderRadius: 10,
    marginRight: 48,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3.84,
    // elevation: 2,
  },
  imageContainer: {width: 120, justifyContent: 'center', alignItems: 'center'},
  launchImage: {
    height: 80,
    width: 80,
    borderRadius: 100,
  },
  launchInfoContainer: {justifyContent: 'space-evenly', padding: 10, flex: 1},
  launchDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 100,
  },
  launchTitle: {
    color: '#034078',
    fontFamily: 'NunitoSans-SemiBold',
    fontSize: 14,
    fontWeight: '600',
  },
  launchValue: {
    color: '#0a1128',
    fontFamily: 'NunitoSans-Bold',
    fontSize: 12,
    fontWeight: '600',
  },
  upcomingLaunchesList: {
    height: 180,
    overflow: 'hidden',
    paddingHorizontal: 12,
  },
  getLaunchesButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },

  searchButton: {
    flexDirection: 'row',
    borderRadius: 10,
    backgroundColor: '#219ebc',
    width: 160,
    height: 50,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  getLaunchesButtonText: {
    fontFamily: 'NunitoSans-Bold',
    fontSize: 15,
    fontWeight: '800',
    color: '#fff',
  },
  modalBackground: {
    height: Dimensions.get('screen').height,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tooltip: {
    height: 220,
    backgroundColor: '#fff',
    width: Dimensions.get('screen').width * 0.8,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    paddingVertical: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  labelContainer: {
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateItemsContainer: {
    flex: 1,
  },
  dateLabel: {
    width: 50,
    fontFamily: 'NunitoSans-SemiBold',
    fontSize: 15,
    color: '#0a1128',
    fontWeight: '600',
  },
  datePicker: {},
  closeIconContainer: {
    position: 'absolute',
    top: -40,
    right: 10,
    height: 40,
    marginVertical: 20,

    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderRadius: 100,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterIconContainer: {
    position: 'absolute',
    top: -40,
    left: 10,
    height: 40,
    marginVertical: 20,

    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderRadius: 100,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeIconText: {
    fontFamily: 'NunitoSans-Bold',
    fontSize: 18,
    fontWeight: '600',
    color: '#000',
  },
  dateItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: 'rgba(142,202,230,0.8)',
    borderWidth: 0.5,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    height: 40,
    marginVertical: 3,
  },
  dateValueText: {
    textAlign: 'center',
    paddingLeft: 5,
    fontFamily: 'NunitoSans-SemiBold',
    fontSize: 14,
    color: '#000',
    fontWeight: '800',
  },
});
